config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/help'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" , registrations: 'registrations'}
  
	
  get 'tags/:tag', to: 'pins#index', as: :tag
  get 'user/:user', to: 'pins#index', as: :user
  resources :pins do
    member do
      put "like", to: "pins#upvote"
      put "down", to: "pins#downvote"
     end
  end
 
  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  
	
	acts_as_votable
  acts_as_taggable
  belongs_to :user
  has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:facebook]
  has_many :pins
	after_create :send_notification
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
	def send_notification
		AdminMailer.new_user(self).deliver
	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def help
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show, :tagged]
  before_filter :set_search
  def set_search
    @search=Pin.tagged_with(params[:q])
  end
  
  def index
    if params[:tag].present?
			@pins = Pin.tagged_with(params[:tag])
    else 
      if params[:user].present?
				@pins = Pin.where(user_id: params[:user])
      else
        if params[:search].present?
          #@pins = Pin.tagged_with(["%#{params[:search]}%"], :any => true)
					@pins = Pin.tagged_with(params[:search], :any => true)
        else
					@pins= Pin.all.order("created_at DESC")
        end
      end
    end
  end
  
  def show
    
  end
  
  def tagged
  if params[:tag].present? 
		@pins = Pin.tagged_with(params[:tag])
  else 
		@pins = Pin.all
  end  
  end
  
  
  def new 
    @pin= current_user.pins.build
  end
  def create
    @pin = current_user.pins.build(pin_params)
    
    if @pin.save
      redirect_to @pin , notice: "Successfully crated new pixl...do a push up."
    else
      render 'new'
    end
    
  end
  
  def edit
    
  end
  
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pixl was Updated...Boot!"
    else
      render 'edit'
    end
  end
  def destroy
    @pin.destroy
    redirect_to root_path
  end
  
  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @pin.downvote_from current_user
    redirect_to :back
  end
  
  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image, :tag_list, :user)
  end
  def find_pin
    @pin= Pin.find(params[:id])
  end
  
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
  
  def update_resource(resource, params)
    if current_user.provider == "facebook"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/_fb.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '811848105578386',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
.container
		.fb-like{"data-href" => request.original_url, "data-layout" => "button", "data-send" => "true", "data-show-faces" => "false", "data-width" => "50"}

app/views/layouts/_google.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63832546-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_jumbo.html.haml
.container
	.jumbotron
		%h1 The Mission:
		%h3 Become the largest collection of combat photos in the world.
		= button_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg", method: :get

app/views/layouts/_search.html.erb
  		<form class="navbar-form navbar-left" role="search">
  			<%= form_tag(pins_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
  		<div class="form-group">
    		<%= text_field_tag :search, params[:search], placeholder: "Search Pixls", class: "form-control" %>
  		</div>
 				<%= submit_tag "Search" , class: "btn btn-default" %>
					
                  
  			<% end %>
			</form>
   
                       
                    

app/views/layouts/_sumo.html.erb
<script src="//load.sumome.com/" data-sumo-site-id="598d5c14266f547cf6559acd2118fdbd0c15b9d7f821b851a780920e3d432fb7" async="async"></script>

app/views/layouts/application.html.haml
!!! 5
%head
	%title VetPixl
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	= render :partial => "layouts/sumo"
	= render :partial => "layouts/google"
%body

	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "VetPixl", root_path
			= render :partial => "layouts/search"
			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "My Pixls", user_path(current_user.id)
					%li= link_to "New Pixl", new_pin_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
					%li= link_to "About", pages_about_path
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
					%li= link_to "About", pages_about_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
	.container
		
		= yield
	

app/views/pages/about.html.erb
<div class="container">
<h1>About Vetpixl.com</h1>
<p>Hey vets, we created this site with the hopes that it will become the largest collection of combat photos ever assembled. Why would you want to 
post your photos here? Because the world needs to see what we actually did, not what the media tells them. </p>

<p>To keep the site clean we implemented a down-vote button. Hit this for spam, ads and shit that doesn't belong. We have to police ourselves.</p>
</div>

app/views/pins/_form.html.haml
=simple_form_for @pin, html: {multipart:true} do |f|
  - if @pin.errors.any?
    #errors
    %h2
    = pluralize(@pin.errors.count, "error")
    prevented this Pin from Saving
    %ul
      - @pin.errors.full_messages.each do |msg|
        %li=msg
  .form_group
  = f.input :image, input_html: {class: 'form_control', input_type:'file', accept: 'image/*', capture: 'camera'} 
  
  .form_group
  = f.input :title, input_html: {class: 'form_control'}
  
  .form_group
  = f.input :tag_list, input_html: {class: 'form_control', placeholder: 'Comma Seperated'}
  
  .form_group
  = f.input :description, input_html: {class: 'form_control'}
  
  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pixl
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
.container
  = render :partial => "layouts/jumbo"
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %p.user
        Submitted by
        = link_to pin.user.name, user_path(pin.user.id)
      .panel-footer
        Tags:
        - pin.tags.each do |tag|
          = link_to tag.name, tag_path(tag.name) , :class =>"label label-default"


     

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create A New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				Tags:
				- @pin.tags.each do |tag|
					= link_to tag.name, tag_path(tag.name) , :class =>"label label-default"
				%p.description= @pin.description
			.panel-footer
				.row
					.col-md-6
						%p.user
							Submitted by
							= link_to @pin.user.name, user_path(@pin.user.id)
					.col-md-6
						.container
							.fb-like{"data-href" => request.original_url, "data-layout" => "button_count", "data-send" => "true", "data-show-faces" => "false", "data-width" => "50"}
						.btn-group.pull-right
							= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.fa.fa-thumbs-o-up
								= @pin.get_upvotes.size
							- if user_signed_in?
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
							= link_to down_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.fa.fa-thumbs-o-down
								= @pin.get_downvotes.size
				.row
					.col-md-6
						.fb-comments{"data-href" => request.original_url, "data-numposts" => "1", "data-colorscheme" => "light", "data-width" => "500"}
 
           